trigger:
- master

jobs:
- job:
  displayName: Linux OpenMP
  pool:
    vmImage: 'ubuntu-18.04'

  strategy:
    matrix:
      Debug:
        BuildType: debug
      Release:
        BuildType: release

  steps:
    - task: Bash@3
      displayName: Install CMake 3.13+
      inputs:
        targetType: 'inline'
        script: |
          set -e
          sh scripts/utils/install_cmake_ubuntu1804.sh

    - task: Bash@3
      displayName: Build stdgpu
      inputs:
        targetType: 'inline'
        script: |
            set -e
            sh scripts/ci/openmp_$(BuildType).sh

    - task: Bash@3
      displayName: Run tests
      inputs:
        targetType: 'inline'
        script: |
            set -e
            sh scripts/run_tests_$(BuildType).sh

- job:
  displayName: Windows OpenMP
  pool:
    vmImage: 'windows-2019'

  strategy:
    matrix:
      Debug:
        BuildType: debug
      Release:
        BuildType: release

  steps:
    - task: Bash@3
      displayName: Build stdgpu
      inputs:
        targetType: 'inline'
        script: |
            set -e
            sh scripts/ci/openmp_$(BuildType).sh

    - task: Bash@3
      displayName: Run tests
      inputs:
        targetType: 'inline'
        script: |
            set -e
            sh scripts/run_tests_$(BuildType).sh
