name: Analysis OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Clang-Tidy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP
        shell: bash
        run: |
          bash tools/ubuntu/install_openmp.sh

      - name: Install clang-tidy
        shell: bash
        run: |
          bash tools/ubuntu/install_clang_tidy.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash tools/dev/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash tools/backend/configure_openmp_clang_tidy.sh

      - name: Build project
        shell: bash
        run: |
          bash tools/build.sh Debug

  Cppcheck:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP
        shell: bash
        run: |
          bash tools/ubuntu/install_openmp.sh

      - name: Install cppcheck
        shell: bash
        run: |
          bash tools/ubuntu/install_cppcheck.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash tools/dev/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash tools/backend/configure_openmp_cppcheck.sh

      - name: Build project
        shell: bash
        run: |
          bash tools/build.sh Debug
