name: Analysis OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Clang-Tidy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenMP
        shell: bash
        run: |
          bash scripts/utils/install_openmp_ubuntu.sh

      - name: Install clang-tidy
        shell: bash
        run: |
          bash scripts/utils/install_clang_tidy_ubuntu.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp_clang_tidy.sh

      - name: Build project
        shell: bash
        run: |
          bash scripts/build.sh Debug

  Cppcheck:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenMP
        shell: bash
        run: |
          bash scripts/utils/install_openmp_ubuntu.sh

      - name: Install cppcheck
        shell: bash
        run: |
          bash scripts/utils/install_cppcheck_ubuntu.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp_cppcheck.sh

      - name: Build project
        shell: bash
        run: |
          bash scripts/build.sh Debug
