name: Docs OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP
        shell: bash
        run: |
          bash tools/ubuntu/install_openmp.sh

      - name: Install docs dependencies
        shell: bash
        run: |
          bash tools/ubuntu/install_docs_dependencies.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash tools/dev/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash tools/backend/configure_openmp_documentation.sh

      - name: Build documentation
        shell: bash
        run: |
          bash tools/dev/build_documentation.sh

      - uses: actions/upload-artifact@v4
        with:
          name: Docs HTML
          path: build/docs/html

  publish:
    name: Upload latest docs to GitHub Pages
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'

    needs:
      - build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: Docs HTML
          path: build/docs/html

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/html
          clean: true
          single-commit: true

  checkdocs:
    if: always()

    needs:
      - build
      - publish

    name: "Check Docs"
    runs-on: ubuntu-22.04

    steps:
    - uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: publish
        jobs: ${{ toJSON(needs) }}
