name: Documentation OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  Doxygen:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install OpenMP
        shell: bash
        run: |
          bash scripts/utils/install_openmp_ubuntu.sh

      - name: Install docs dependencies
        shell: bash
        run: |
          bash scripts/utils/install_docs_dependencies_ubuntu.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp_documentation.sh

      - name: Build documentation
        shell: bash
        run: |
          bash scripts/utils/build_documentation.sh

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs/html
          clean: true
          single-commit: true
        if: github.event_name != 'pull_request'
