name: Documentation OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Doxygen:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenMP
        shell: bash
        run: |
          sh scripts/utils/install_openmp_ubuntu2004.sh

      - name: Install doxygen dependencies
        shell: bash
        run: |
          sh scripts/utils/install_doxygen_dependencies_ubuntu2004.sh

      - name: Download dependencies
        shell: bash
        run: |
          sh scripts/utils/download_dependencies.sh

      - name: Download doxygen
        shell: bash
        run: |
          sh scripts/utils/download_doxygen.sh

      - name: Configure project
        shell: bash
        run: |
          sh scripts/ci/configure_openmp_documentation.sh

      - name: Build documentation
        shell: bash
        run: |
          sh scripts/utils/build_documentation.sh
