name: Ubuntu OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Ubuntu-2004:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        CXX: [g++, clang++]
        BuildType: [Debug, Release]
        SharedLibs: [ON, OFF]
        Use32BitIndex: [ON, OFF]
        include:
          - CXX: g++
            CC: gcc
          - CXX: clang++
            CC: clang

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP
        shell: bash
        run: |
          bash tools/ubuntu/install_openmp.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash tools/dev/download_dependencies.sh

      - name: Set C/C++ compiler
        shell: bash
        run: |
          bash tools/ubuntu/set_cxx_compiler.sh ${{ matrix.CC }} ${{ matrix.CXX }}

      - name: Configure project
        shell: bash
        run: |
          bash tools/backend/configure_openmp.sh ${{ matrix.BuildType }} -DSTDGPU_BUILD_SHARED_LIBS=${{ matrix.SharedLibs }} -DSTDGPU_USE_32_BIT_INDEX=${{ matrix.Use32BitIndex }}

      - name: Build project
        shell: bash
        run: |
          bash tools/build.sh ${{ matrix.BuildType }}

      - name: Run tests
        shell: bash
        run: |
          bash tools/run_tests.sh ${{ matrix.BuildType }}

      - name: Verify headers
        shell: bash
        run: |
          bash tools/dev/verify_headers.sh

      - name: Install project
        shell: bash
        run: |
          bash tools/install.sh ${{ matrix.BuildType }}

      - name: Check linking to installed project
        shell: bash
        run: |
          bash tools/backend/check_install_openmp.sh ${{ matrix.BuildType }}

      - name: Uninstall project
        shell: bash
        run: |
          bash tools/uninstall.sh ${{ matrix.BuildType }}

  Ubuntu-2204:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        CXX: [g++, clang++]
        BuildType: [Debug, Release]
        SharedLibs: [ON, OFF]
        Use32BitIndex: [ON, OFF]
        include:
          - CXX: g++
            CC: gcc
          - CXX: clang++
            CC: clang

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenMP
        shell: bash
        run: |
          bash tools/ubuntu/install_openmp.sh

      - name: Download dependencies
        shell: bash
        run: |
          bash tools/dev/download_dependencies.sh

      - name: Set C/C++ compiler
        shell: bash
        run: |
          bash tools/ubuntu/set_cxx_compiler.sh ${{ matrix.CC }} ${{ matrix.CXX }}

      - name: Configure project
        shell: bash
        run: |
          bash tools/backend/configure_openmp.sh ${{ matrix.BuildType }} -DSTDGPU_BUILD_SHARED_LIBS=${{ matrix.SharedLibs }} -DSTDGPU_USE_32_BIT_INDEX=${{ matrix.Use32BitIndex }}

      - name: Build project
        shell: bash
        run: |
          bash tools/build.sh ${{ matrix.BuildType }}

      - name: Run tests
        shell: bash
        run: |
          bash tools/run_tests.sh ${{ matrix.BuildType }}

      - name: Verify headers
        shell: bash
        run: |
          bash tools/dev/verify_headers.sh

      - name: Install project
        shell: bash
        run: |
          bash tools/install.sh ${{ matrix.BuildType }}

      - name: Check linking to installed project
        shell: bash
        run: |
          bash tools/backend/check_install_openmp.sh ${{ matrix.BuildType }}

      - name: Uninstall project
        shell: bash
        run: |
          bash tools/uninstall.sh ${{ matrix.BuildType }}
