name: Windows OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Windows:
    runs-on: windows-2019

    strategy:
      matrix:
        BuildType: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp.sh ${{ matrix.BuildType }}

      - name: Build project
        shell: bash
        run: |
          bash scripts/build.sh ${{ matrix.BuildType }}

      - name: Run tests
        shell: bash
        run: |
          bash scripts/run_tests.sh ${{ matrix.BuildType }}
