name: Windows OpenMP

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Windows-2019:
    runs-on: windows-2019

    strategy:
      matrix:
        BuildType: [Debug, Release]
        SharedLibs: [ON, OFF]
        Use32BitIndex: [ON, OFF]

    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp.sh ${{ matrix.BuildType }} -DSTDGPU_BUILD_SHARED_LIBS=${{ matrix.SharedLibs }} -DSTDGPU_USE_32_BIT_INDEX=${{ matrix.Use32BitIndex }} -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE

      - name: Build project
        shell: bash
        run: |
          bash scripts/build.sh ${{ matrix.BuildType }}

      - name: Run tests
        shell: bash
        run: |
          bash scripts/run_tests.sh ${{ matrix.BuildType }}

      - name: Verify headers
        shell: bash
        run: |
          bash scripts/utils/verify_headers.sh

      - name: Install project
        shell: bash
        run: |
          bash scripts/install.sh ${{ matrix.BuildType }}

      - name: Check linking to installed project
        shell: bash
        run: |
          bash scripts/ci/check_install_openmp.sh ${{ matrix.BuildType }}

      - name: Uninstall project
        shell: bash
        run: |
          bash scripts/uninstall.sh ${{ matrix.BuildType }}

  Windows-2022:
    runs-on: windows-2022

    strategy:
      matrix:
        BuildType: [Debug, Release]
        SharedLibs: [ON, OFF]
        Use32BitIndex: [ON, OFF]

    steps:
      - uses: actions/checkout@v3

      - name: Download dependencies
        shell: bash
        run: |
          bash scripts/utils/download_dependencies.sh

      - name: Configure project
        shell: bash
        run: |
          bash scripts/ci/configure_openmp.sh ${{ matrix.BuildType }} -DSTDGPU_BUILD_SHARED_LIBS=${{ matrix.SharedLibs }} -DSTDGPU_USE_32_BIT_INDEX=${{ matrix.Use32BitIndex }} -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE

      - name: Build project
        shell: bash
        run: |
          bash scripts/build.sh ${{ matrix.BuildType }}

      - name: Run tests
        shell: bash
        run: |
          bash scripts/run_tests.sh ${{ matrix.BuildType }}

      - name: Verify headers
        shell: bash
        run: |
          bash scripts/utils/verify_headers.sh

      - name: Install project
        shell: bash
        run: |
          bash scripts/install.sh ${{ matrix.BuildType }}

      - name: Check linking to installed project
        shell: bash
        run: |
          bash scripts/ci/check_install_openmp.sh ${{ matrix.BuildType }}

      - name: Uninstall project
        shell: bash
        run: |
          bash scripts/uninstall.sh ${{ matrix.BuildType }}
